# Project Information
site_name: PIQUE
site_url: https://MSUSEL.github.io/Pique-Lite/

# Repository
repo_name: MSUSEL/Pique-Lite
repo_url: https://github.com/MSUSEL/Pique-Lite

# Configuration
theme:
  name: material
  features:
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - content.tooltips
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow

  font:
    text: Roboto
    code: Roboto Mono
  logo: https://raw.githubusercontent.com/MSUSEL/msusel-pique-visualizer/refactorZiyi/src/assets/PIQUE_svg.svg
  language: en
  palette:
    # Dark Mode
    - scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Dark mode

    # Light Mode
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Light mode

# Extensions
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
      - name: mermaid
        class: mermaid
        format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

# Page tree
nav:
  - PIQUE: index.md
  - Developer Notes: developer-notes/setup.md
  - User Guide:
    - Overview: user-guide/index.md
    - Input Schema: 
      - Overview: user-guide/input-schema/input-schema.md
      - Handling Input Errors: user-guide/input-schema/input-errors.md
    - Core Features: 
      - File Upload: user-guide/core-features/file-upload.md
      - Initial Display: user-guide/core-features/initial-display.md
      - Understanding the Metrics: user-guide/core-features/interpreting-metrics.md
    - Advanced Features: 
      - Tree Display: user-guide/advanced-features/tree-display.md
      - Adjusting Category Weights: user-guide/advanced-features/adjusting-weights.md
      - Understanding the Metrics: user-guide/advanced-features/interpreting-metrics.md
  - Tutorials:
    - Basic Example: tutorials/basic-example.md
    - Advanced Example: tutorials/adv-example.md
  - FAQ and Troubleshooting: 
    - Frequently Asked Questions: faq-troubleshooting/faq.md
    - Common Issues: faq-troubleshooting/common-issues.md

extra_css:
  - assets/docs-theme.css
