# Project Information
site_name: PIQUE-Lite
site_url: https://MSUSEL.github.io/Pique-Lite/

# Repository
repo_name: MSUSEL/Pique-Lite
repo_url: https://github.com/MSUSEL/Pique-Lite

# Configuration
theme:
  name: material
  features:
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - content.tooltips
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.path
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate


  font:
    text: Roboto
    code: Roboto Mono
  logo: https://raw.githubusercontent.com/MSUSEL/msusel-pique-visualizer/refactorZiyi/src/assets/PIQUE_svg.svg
  language: en
  palette:
    # Dark Mode
    - scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Dark mode

    # Light Mode
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Light mode

# Extensions
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

# Page tree
nav:
  - Home: index.md
  - PIQUE-Lite:
    - Introduction: pique-lite/intro.md
    - Getting Started: pique-lite/getting-started.md
    - User Guide: pique-lite/user-guide.md
    - Advanced Features: pique-lite/advanced-features.md
  # - Getting started
  # - PIQUE-Lite
  # - PIQUE-Visualizer
  # - Input File Schema Requirements
  
# Page tree
# nav:
#   - Home: index.md
#   - Getting started:
#     - Installation: getting-started.md
#     - Creating your site: creating-your-site.md
#     - Publishing your site: publishing-your-site.md
#     - Customization: customization.md
#     - Conventions: conventions.md
#     - Browser support: browser-support.md
#     - Enterprise feedback: enterprise-support.md
#     - Philosophy: philosophy.md
#     - Alternatives: alternatives.md
#     - License: license.md
#     - Tutorials:
#       - tutorials/index.md
#       - "Blogs":
#         - tutorials/blogs/basic.md
#         - tutorials/blogs/navigation.md
#         - tutorials/blogs/engage.md
#       - "Social cards":
#         - tutorials/social/basic.md
#         - tutorials/social/custom.md
#     - Changelog:
#       - changelog/index.md
#       - How to upgrade: upgrade.md
#   - Setup:
#     - setup/index.md
#     - Changing the colors: setup/changing-the-colors.md
#     - Changing the fonts: setup/changing-the-fonts.md
#     - Changing the language: setup/changing-the-language.md
#     - Changing the logo and icons: setup/changing-the-logo-and-icons.md
#     - Ensuring data privacy: setup/ensuring-data-privacy.md
#     - Setting up navigation: setup/setting-up-navigation.md
#     - Setting up site search: setup/setting-up-site-search.md
#     - Setting up site analytics: setup/setting-up-site-analytics.md
#     - Setting up social cards: setup/setting-up-social-cards.md
#     - Setting up a blog: setup/setting-up-a-blog.md
#     - Setting up tags: setup/setting-up-tags.md
#     - Setting up versioning: setup/setting-up-versioning.md
#     - Setting up the header: setup/setting-up-the-header.md
#     - Setting up the footer: setup/setting-up-the-footer.md
#     - Adding a git repository: setup/adding-a-git-repository.md
#     - Adding a comment system: setup/adding-a-comment-system.md
#     - Building an optimized site: setup/building-an-optimized-site.md
#     - Building for offline usage: setup/building-for-offline-usage.md
#     - Extensions:
#       - setup/extensions/index.md
#       - Python Markdown: setup/extensions/python-markdown.md
#       - Python Markdown Extensions: setup/extensions/python-markdown-extensions.md
#   - Plugins:
#     - plugins/index.md
#     - Blog: plugins/blog.md
#     - Group: plugins/group.md
#     - Info: plugins/info.md
#     - Meta: plugins/meta.md
#     - Offline: plugins/offline.md
#     - Optimize: plugins/optimize.md
#     - Privacy: plugins/privacy.md
#     - Projects: plugins/projects.md
#     - Search: plugins/search.md
#     - Social: plugins/social.md
#     - Tags: plugins/tags.md
#     - Typeset: plugins/typeset.md
#     - Requirements:
#       - Image processing: plugins/requirements/image-processing.md
#       - Caching: plugins/requirements/caching.md
#   - Reference:
#     - reference/index.md
#     - Admonitions: reference/admonitions.md
#     - Annotations: reference/annotations.md
#     - Buttons: reference/buttons.md
#     - Code blocks: reference/code-blocks.md
#     - Content tabs: reference/content-tabs.md
#     - Data tables: reference/data-tables.md
#     - Diagrams: reference/diagrams.md
#     - Footnotes: reference/footnotes.md
#     - Formatting: reference/formatting.md
#     - Grids: reference/grids.md
#     - Icons, Emojis: reference/icons-emojis.md
#     - Images: reference/images.md
#     - Lists: reference/lists.md
#     - Math: reference/math.md
#     - Tooltips: reference/tooltips.md
#   - Insiders:
#     - insiders/index.md
#     - Why sponsor us: insiders/why-sponsor-us.md
#     - What's in it for you: insiders/benefits.md
#     - Who is sponsoring: insiders/our-sponsors.md
#     - Sponsoring tiers: insiders/sponsoring-tiers.md
#     - How to sponsor: insiders/how-to-sponsor.md
#     - Additional information:
#       - Payment and billing: insiders/payment-and-billing.md
#       - Access management: insiders/access-management.md
#       - Runtime and cancellation: insiders/runtime-and-cancellation.md
#       - Privacy: insiders/privacy.md
#       - License: insiders/license.md
#       - Support: support.md
#     - Using Insiders:
#       - Getting started: insiders/getting-started.md
#     - Changelog:
#       - insiders/changelog/index.md
#       - How to upgrade: insiders/upgrade.md
#   - Community:
#     - Contributing:
#       - contributing/index.md
#       - Reporting a bug: contributing/reporting-a-bug.md
#       - Reporting a docs issue: contributing/reporting-a-docs-issue.md
#       - Requesting a change: contributing/requesting-a-change.md
#       - Adding translations: contributing/adding-translations.md
#       - Making a pull request: contributing/making-a-pull-request.md
#       - Asking a question: https://github.com/squidfunk/mkdocs-material/discussions
#     - Guides:
#       - Creating a reproduction: guides/creating-a-reproduction.md
#     - Community experts program:
#       - insiders/community-experts-program/index.md
#   - Blog:
#     - blog/index.md 

extra_css:
  - docs-theme.css
