// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/versionDetails/project/:projectId/version/:versionId": {
    params: {
      "projectId": string;
      "versionId": string;
    };
  };
  "/project/:projectId": {
    params: {
      "projectId": string;
    };
  };
  "/overview": {
    params: {};
  };
  "/settings": {
    params: {};
  };
  "/about": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/versionDetails/project/:projectId/version/:versionId" | "/project/:projectId" | "/overview" | "/settings" | "/about";
  };
  "routes/_dashboard.tsx": {
    id: "routes/_dashboard";
    page: "/versionDetails/project/:projectId/version/:versionId" | "/project/:projectId" | "/overview" | "/settings";
  };
  "routes/_dashboard.versionDetails.project.$projectId.version.$versionId.tsx": {
    id: "routes/_dashboard.versionDetails.project.$projectId.version.$versionId";
    page: "/versionDetails/project/:projectId/version/:versionId";
  };
  "routes/_dashboard.project.$projectId.tsx": {
    id: "routes/_dashboard.project.$projectId";
    page: "/project/:projectId";
  };
  "routes/_dashboard.overview.tsx": {
    id: "routes/_dashboard.overview";
    page: "/overview";
  };
  "routes/_dashboard.settings.tsx": {
    id: "routes/_dashboard.settings";
    page: "/settings";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/about.tsx": {
    id: "routes/about";
    page: "/about";
  };
};

type RouteModules = {
  "root": typeof import("./src/root.tsx");
  "routes/_dashboard": typeof import("./src/routes/_dashboard.tsx");
  "routes/_dashboard.versionDetails.project.$projectId.version.$versionId": typeof import("./src/routes/_dashboard.versionDetails.project.$projectId.version.$versionId.tsx");
  "routes/_dashboard.project.$projectId": typeof import("./src/routes/_dashboard.project.$projectId.tsx");
  "routes/_dashboard.overview": typeof import("./src/routes/_dashboard.overview.tsx");
  "routes/_dashboard.settings": typeof import("./src/routes/_dashboard.settings.tsx");
  "routes/_index": typeof import("./src/routes/_index.tsx");
  "routes/about": typeof import("./src/routes/about.tsx");
};